name: taskmallow
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#ffffff"
  android_12:
    color: "#ffffff"
  image: "lib/assets/images/launcher_icon.png"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  shared_preferences: ^2.1.1
  intl: ^0.18.0
  image_picker: ^0.8.8
  permission_handler: ^10.3.0
  firebase_core: ^2.14.0
  flutter_local_notifications: ^9.2.0
  firebase_messaging: ^14.6.3
  http: ^0.13.5
  url_launcher: ^6.1.11
  cloud_functions: ^4.3.3
  firebase_storage: ^11.2.3
  cloud_firestore: ^4.8.1
  flutter_riverpod: ^2.3.6
  uuid: ^3.0.7
  flutter_native_splash: ^2.3.1
  device_info_plus: ^9.0.2
  animations: ^2.0.7
  package_info_plus: ^4.0.2
  firebase_database: ^10.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  
flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/icons/solid/
    - lib/assets/icons/regular/
    - lib/localization/languages/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Regular.ttf